export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED_SUCCESS = 'LOAD_USER_SUCCESS';
export const USER_LOADED_FAIL = 'LOAD_USER_FAIL';
export const LOGOUT = 'LOGOUT';
export const AUTHENTICATED_SUCCESS = 'LOGOUT';
export const AUTHENTICATED_FAIL = 'LOGOUT';

